QUESTION_PAIRS = [
  { "normal": "How many tabs do you usually have open on your browser?", "imposter": "How many browser bookmarks do you check weekly?" },
  { "normal": "What do you usually eat when you're super hungry?", "imposter": "What’s a food you eat when you’re bored?" },
  { "normal": "How much time do you spend on social media each day?", "imposter": "How many times a day do you open Instagram or TikTok?" },
  { "normal": "What's your favorite place to relax indoors?", "imposter": "Where do you go when you want to be alone?" },
  { "normal": "How many group chats are you active in right now?", "imposter": "How many unread group chats are on your phone?" },
  { "normal": "What kind of shoes do you wear the most?", "imposter": "What kind of shoes are hardest for you to get rid of?" },
  { "normal": "How many alarms do you set to wake up?", "imposter": "How many times do you usually snooze your alarm?" },
  { "normal": "What’s your favorite thing to watch when you’re tired?", "imposter": "What’s a show you keep watching even if you’re not really into it?" },
  { "normal": "How much water do you usually drink in a day?", "imposter": "How many cups of anything do you drink daily, roughly?" },
  { "normal": "What's your go-to breakfast on weekdays?", "imposter": "What’s something you eat in the morning only when you have time?" },
  { "normal": "How often do you go out to eat in a week?", "imposter": "How many food delivery apps are on your phone?" },
  { "normal": "Which season do you enjoy the most?", "imposter": "What kind of weather do you absolutely avoid going out in?" },
  { "normal": "How many photos are in your phone gallery?", "imposter": "How many screenshots are on your phone right now?" },
  { "normal": "What’s a snack you keep stocked at home?", "imposter": "What’s something you only buy as a treat for yourself?" },
  { "normal": "How long does your ideal vacation last?", "imposter": "How many days off work or school would feel like a real break?" },
  { "normal": "What’s the most fun way to spend a Sunday?", "imposter": "What’s the laziest Sunday you’ve had recently?" },
  { "normal": "What kind of clothes do you wear most often?", "imposter": "What’s a piece of clothing you own but rarely wear?" },
  { "normal": "How many apps do you use daily?", "imposter": "How many apps are you currently logged into?" },
  { "normal": "What do you usually do right before bed?", "imposter": "What’s something you do in bed but shouldn’t?" },
  { "normal": "How many people do you talk to regularly?", "imposter": "How many people text you first?" },
  { "normal": "What's your favorite fast food order?", "imposter": "What’s something you always customize in your food order?" },
  { "normal": "How long could you stay offline before it bothered you?", "imposter": "How many hours a day do you actually stay offline?" },
  { "normal": "What’s your favorite time of day?", "imposter": "What’s the worst time to call you?" },
  { "normal": "How many unread notifications are on your phone?", "imposter": "How many notifications do you usually clear at once?" },
  { "normal": "What's your favorite thing to do with friends?", "imposter": "What do you usually suggest when no one has a plan?" },
  { "normal": "How many streaming services do you use?", "imposter": "How many shows are you currently halfway through?" },
  { "normal": "What do you usually do when you're waiting in line?", "imposter": "What’s something you do only when you’re bored in public?" },
  { "normal": "What’s a movie you’ve rewatched more than 3 times?", "imposter": "What’s a movie you’ve watched but never finished?" },
  { "normal": "How many minutes does your average shower take?", "imposter": "How long do you spend getting ready in total?" },
  { "normal": "What's your go-to comfort food?", "imposter": "What’s a food you love but rarely admit out loud?" },
  { "normal": "How many different outfits do you wear in a typical week?", "imposter": "How many shirts do you have in your closet right now?" },
  { "normal": "What’s your favorite way to spend a rainy day?", "imposter": "What’s something you only do when the weather is bad?" },
  { "normal": "How many contacts do you have saved in your phone?", "imposter": "How many people have custom ringtones or names in your contacts?" },
  { "normal": "What kind of movies do you usually pick?", "imposter": "What kind of movies do you avoid no matter what?" },
  { "normal": "How many hours of sleep do you usually get?", "imposter": "How many times do you wake up in the middle of the night?" },
  { "normal": "What’s your usual mode of transport during the week?", "imposter": "What kind of transport do you use when you're in a rush?" },
  { "normal": "What’s a dish you order at least once a month?", "imposter": "What’s a food you only get when someone else pays?" },
  { "normal": "How many times a week do you exercise?", "imposter": "How many minutes of walking do you do on an average day?" },
  { "normal": "What’s your favorite thing to do on your phone?", "imposter": "What’s an app you use a lot but don’t talk about?" },
  { "normal": "How many times do you check the time in an hour when you're bored?", "imposter": "How often do you check your phone just to avoid people?" },
  { "normal": "Where do you usually sit when you’re at a cafe?", "imposter": "What’s your favorite spot when you're trying not to be noticed?" },
  { "normal": "How many times a week do you eat out?", "imposter": "How often do you eat the same thing two days in a row?" },
  { "normal": "What’s your favorite thing to listen to while working?", "imposter": "What’s something you play in the background just for noise?" },
  { "normal": "How many notifications do you get in a day?", "imposter": "How many times do you mute your phone in a day?" },
  { "normal": "What kind of bag or backpack do you use regularly?", "imposter": "What’s something unusual that’s always in your bag?" },
  { "normal": "How many browser tabs are open on your phone right now?", "imposter": "How many different browsers do you use on your phone?" },
  { "normal": "What's your go-to comfort TV show?", "imposter": "What’s a show you’ve never finished but keep meaning to?" },
  { "normal": "How long does it take you to get ready in the morning?", "imposter": "How many steps are in your morning routine?" },
  { "normal": "What’s your favorite snack at the movies?", "imposter": "What’s a snack you sneak into the theater?" },
  { "normal": "How many playlists do you have saved?", "imposter": "How many playlists have you actually listened to recently?" },
  { "normal": "What’s something you always pack when traveling?", "imposter": "What’s something you only pack but rarely use?" },
  { "normal": "How many unread messages are in your chats?", "imposter": "How many group chats have you muted permanently?" },
  { "normal": "What’s your usual drink order at a café?", "imposter": "What’s a drink you avoid even if it's free?" },
  { "normal": "How often do you change your bedsheets?", "imposter": "How many pillows do you sleep with?" },
  { "normal": "What’s your favorite online store or app to shop from?", "imposter": "What’s the last thing you added to a wishlist but didn’t buy?" },
  { "normal": "How many devices are connected to your Wi-Fi right now?", "imposter": "How many screens do you usually use at once?" },
  { "normal": "What do you usually do during lunch breaks?", "imposter": "What’s something you do during breaks that people wouldn’t guess?" },
  { "normal": "How many calls do you make in a day?", "imposter": "How many people do you regularly ignore calls from?" },
  { "normal": "What’s your go-to lazy dinner?", "imposter": "What’s a meal you make that takes exactly zero effort?" },
  { "normal": "How many pairs of shoes do you actually wear?", "imposter": "How many shoes do you own that are just collecting dust?" },
  { "normal": "How many hours do you spend watching videos per week?", "imposter": "How many YouTube channels are you subscribed to?" },
  { "normal": "What's your favorite thing to do on a long weekend?", "imposter": "What’s something you only do when you’ve got absolutely nothing planned?" },
  { "normal": "How many times a day do you brush your teeth?", "imposter": "How many different products do you use in your bathroom routine?" },
  { "normal": "What's your favorite thing to cook when you're short on time?", "imposter": "What’s a food you keep ingredients for, just in case?" },
  { "normal": "How many people live in your house?", "imposter": "How many keys do you carry every day?" },
  { "normal": "What do you usually do on a video call with friends?", "imposter": "What’s something you only do on camera but not in real life?" },
  { "normal": "How often do you clean your room?", "imposter": "How many things in your room are out of place right now?" },
  { "normal": "How many passwords do you actually remember?", "imposter": "How many accounts do you reuse the same password for?" },
  { "normal": "What's your favorite way to spend alone time?", "imposter": "What’s something you never do when others are around?" },
  { "normal": "How many videos are saved in your ‘watch later’ list?", "imposter": "How many videos do you rewatch often?" },
  { "normal": "What’s your go-to breakfast on weekends?", "imposter": "What’s a breakfast you only eat when traveling?" },
  { "normal": "How many times do you usually check your bank account per week?", "imposter": "How many subscriptions are silently draining your money?" },
  { "normal": "What's the longest you've gone without using your phone?", "imposter": "What’s the longest you've stayed in airplane mode?" },
  { "normal": "How many photos do you take in a week?", "imposter": "How many selfies do you delete before posting one?" },
  { "normal": "What’s your favorite type of dessert?", "imposter": "What’s a dessert you like but rarely order?" },
  { "normal": "How many times a day do you check the mirror?", "imposter": "How many times do you change your outfit before leaving the house?" },
  { "normal": "What’s your favorite item in your room?", "imposter": "What’s something in your room you’ve been meaning to throw away?" },
  { "normal": "How many hours of screen time do you rack up daily?", "imposter": "How many hours do you feel *guilty* about using your phone?" },
  { "normal": "What’s your ideal number of vacation days per year?", "imposter": "How many days off do you usually waste doing nothing?" },
  { "normal": "What’s your favorite kind of street food?", "imposter": "What’s something you only eat when you’re with friends, not alone?" },
  { "normal": "How often do you message your close friends?", "imposter": "How many conversations are you currently ignoring?" },
  { "normal": "How many hours do you usually sleep on weekends?", "imposter": "How many alarms do you set just for sleeping in?" },
  { "normal": "What’s your favorite song to listen to on repeat?", "imposter": "What’s a song you love but don’t want people to know?" },
  { "normal": "How many bags or wallets do you own?", "imposter": "How many things do you carry that aren’t really necessary?" },
  { "normal": "What’s something you always check before leaving the house?", "imposter": "What’s something you always forget when leaving?" },
  { "normal": "How many group chats are you in?", "imposter": "How many group chats are just memes and nothing else?" },
  { "normal": "What’s your go-to way to avoid small talk?", "imposter": "What’s something you pretend to be doing to look busy?" },
  { "normal": "How many times do you check your appearance in a day?", "imposter": "How many times do you fix your hair or clothes in public?" },
  { "normal": "What’s your favorite guilty pleasure snack?", "imposter": "What’s a snack you eat only when no one’s watching?" },
  { "normal": "How many hours do you usually work or study daily?", "imposter": "How many hours do you *actually* focus without distraction?" },
  { "normal": "How many hours a day do you wear headphones?", "imposter": "How many pairs of earphones or headphones do you own?" },
  { "normal": "What’s your favorite kind of sandwich?", "imposter": "What’s a sandwich filling you secretly hate?" },
  { "normal": "How many games do you have installed right now?", "imposter": "How many games do you actually play regularly?" },
  { "normal": "What’s the first app you open in the morning?", "imposter": "What’s an app you keep but rarely use?" },
  { "normal": "How many emails do you read in a day?", "imposter": "How many unread promotional emails are in your inbox?" },
  { "normal": "What’s your favorite way to spend a lazy evening?", "imposter": "What’s something you do late at night that you'd never do in the morning?" },
  { "normal": "How many times do you charge your phone each day?", "imposter": "How many battery-saving tips do you actually use?" },
  { "normal": "What's your usual way of commuting?", "imposter": "What's the longest time you've ever spent stuck in traffic?" },
  { "normal": "How many beverages do you drink in a day?", "imposter": "How many cups of coffee or tea is too many for you?" },
  { "normal": "What’s a show you binge-watched recently?", "imposter": "What’s a show you watch slowly on purpose?" },
  { "normal": "How many times do you shop online each month?", "imposter": "How many online shopping carts have items just sitting there?" },
  { "normal": "What’s your favorite time to go for a walk?", "imposter": "What time of day do you most avoid going outside?" },
  { "normal": "How many minutes do you usually scroll before sleeping?", "imposter": "How many times do you tell yourself 'just five more minutes'?" },
  { "normal": "What's your favorite thing to do when you're stuck indoors?", "imposter": "What's something you only do when you're completely out of ideas?" },
  { "normal": "How many close friends do you talk to every week?", "imposter": "How many people do you consider close but barely talk to?" },
  { "normal": "What’s your favorite kind of pizza topping?", "imposter": "What’s a pizza topping you’ll eat but never order yourself?" },
  { "normal": "How many bags do you carry on a normal day?", "imposter": "How many pockets do you actually use in your clothes?" },
  { "normal": "What’s your ideal number of roommates?", "imposter": "How many people have you actually lived with so far?" },
  { "normal": "How many times do you eat out in a month?", "imposter": "How many food loyalty programs or reward apps are you signed up for?" },
  { "normal": "What kind of music do you listen to while working?", "imposter": "What’s a genre you secretly enjoy but rarely admit to?" },
  { "normal": "How many unread messages do you ignore for days?", "imposter": "How many people have you ghosted unintentionally?" },
  { "normal": "What’s your usual bedtime on weekdays?", "imposter": "What’s the latest you've stayed up on a work or school night?" },
  { "normal": "How many photos do you back up regularly?", "imposter": "How many old photos have you been meaning to delete?" },
  { "normal": "What’s your favorite thing to do on a day off?", "imposter": "What’s something you plan for days off but never actually do?" },
  { "normal": "How many online accounts do you actively use?", "imposter": "How many accounts have you forgotten the password to?" },
  { "normal": "What’s a guilty pleasure show you secretly enjoy?", "imposter": "What’s a show you pretend you’ve never seen but actually love?" },
  { "normal": "How many browser extensions are you using?", "imposter": "How many apps or tools do you have open at the same time right now?" },
  { "normal": "What’s your favorite junk food?", "imposter": "What’s something unhealthy you eat but pretend isn’t that bad?" },
  { "normal": "How many friends do you regularly hang out with in person?", "imposter": "How many people have you drifted away from without noticing?" },
  { "normal": "What’s the longest time you’ve ever stayed in pajamas?", "imposter": "What’s something you do in pajamas that feels a bit too lazy?" },
  { "normal": "How many times do you check your phone before getting out of bed?", "imposter": "How many apps do you open before you even get out of bed?" },
  { "normal": "What’s your favorite way to kill time during travel?", "imposter": "What’s something you always carry but never end up using while traveling?" },
  { "normal": "How many different meals do you cook in a typical week?", "imposter": "How many food items in your kitchen are unopened right now?" },
  { "normal": "What’s your go-to guilty pleasure song?", "imposter": "What’s a song you’d never play in front of someone else?" },
  { "normal": "How many hours a week do you spend on video calls?", "imposter": "How many video meetings do you completely zone out in?" },
  { "normal": "What’s your favorite way to spend a public holiday?", "imposter": "What’s something you always plan to do on holidays but never get to?" },
  { "normal": "How many items are on your to-do list today?", "imposter": "How many things have been on your to-do list for over a week?" },
  { "normal": "What’s your favorite drink when you're out with friends?", "imposter": "What’s a drink you always regret ordering?" },
  { "normal": "How many emails are in your spam folder?", "imposter": "How many email accounts do you still use regularly?" },
  { "normal": "How many photos do you post in a typical month?", "imposter": "How many photos do you take but never share with anyone?" },
  { "normal": "What’s your favorite thing to do during a power cut?", "imposter": "What’s something that completely ruins your mood when the power goes out?" },
  { "normal": "How many devices do you charge overnight?", "imposter": "How many chargers do you keep next to your bed?" },
  { "normal": "What’s your favorite thing to do when you're alone at home?", "imposter": "What’s something you only do when you’re sure no one is watching?" },
  { "normal": "How many books have you finished this year?", "imposter": "How many books have you started and not finished?" },
  { "normal": "What’s your go-to way to de-stress after a long day?", "imposter": "What’s something you do to unwind that others might find odd?" },
  { "normal": "How many tabs are open in your browser right now?", "imposter": "How many tabs is *too many* before you feel the need to clean up?" },
  { "normal": "What’s your favorite snack combo?", "imposter": "What’s a food combo you like but are embarrassed to admit?" },
  { "normal": "How many times a week do you do laundry?", "imposter": "How many times have you reworn something to avoid doing laundry?" },
  { "normal": "What’s the longest you’ve gone without replying to a message?", "imposter": "What’s something you’ve read but never responded to, on purpose?" },
  { "normal": "How many browser bookmarks do you actually use?", "imposter": "How many do you keep just in case?" },
  { "normal": "What’s your favorite way to stay active?", "imposter": "What’s a workout or exercise you’ve completely given up on?" },
  { "normal": "How many notifications do you get during dinner time?", "imposter": "How many apps do you mute specifically during meals?" },
  { "normal": "What’s your favorite kind of phone case?", "imposter": "What’s something unusual you’ve kept inside a phone case?" },
  { "normal": "How many times a month do you go shopping offline?", "imposter": "How many times have you gone out just to browse, not buy?" },
  { "normal": "What’s the most-used feature on your phone?", "imposter": "What’s something on your phone you never use but never delete?" },
  { "normal": "How many minutes does it take you to get out of bed after waking?", "imposter": "How many alarms do you sleep through on average?" },
  { "normal": "What’s your favorite thing to do when you can't sleep?", "imposter": "What’s something you’ve done late at night that you regretted in the morning?" },
  { "normal": "How many bags or containers are in your fridge right now?", "imposter": "How many leftovers do you avoid eating?" },
  { "normal": "What’s your favorite way to organize your stuff?", "imposter": "What’s an area in your room you always ignore during cleaning?" },
  { "normal": "How many screens do you use at the same time?", "imposter": "How many screens around you are currently turned on?" },
  { "normal": "How many songs do you have downloaded on your phone?", "imposter": "How many songs do you skip before finding the right vibe?" },
  { "normal": "What’s your favorite midnight snack?", "imposter": "What’s something you only eat after everyone else is asleep?" },
  { "normal": "How many steps do you walk on an average day?", "imposter": "How many steps do you feel guilty *not* hitting daily?" },
  { "normal": "What’s your favorite piece of tech you own?", "imposter": "What’s a gadget you bought but barely use?" },
  { "normal": "How many social media apps do you check daily?", "imposter": "How many social apps are just sitting unused on your phone?" },
  { "normal": "What’s your go-to dish when you cook for others?", "imposter": "What’s something you cook that you never serve guests?" },
  { "normal": "How many tabs are open on your laptop right now?", "imposter": "How many tabs have been open for over a week?" },
  { "normal": "What’s your favorite kind of footwear?", "imposter": "What’s a pair of shoes you keep but never wear outside?" },
  { "normal": "How many screens do you look at during work hours?", "imposter": "How many times do you switch screens to avoid doing work?" },
  { "normal": "What’s your favorite kind of celebration?", "imposter": "What’s a type of party or event you secretly try to skip?" },
  { "normal": "How many streaming shows are you watching right now?", "imposter": "How many shows are you watching just to finish, not enjoy?" },
  { "normal": "How often do you switch your phone wallpaper?", "imposter": "How many wallpapers have you saved but never used?" },
  { "normal": "What’s your favorite chore around the house?", "imposter": "What’s a chore you pretend to forget?" },
  { "normal": "How many photos are in your phone’s trash folder?", "imposter": "How many photos do you keep even though you don't need them?" },
  { "normal": "How many different group chats are active right now?", "imposter": "How many group chats are just memes and emojis?" },
  { "normal": "What’s the first thing you do after waking up?", "imposter": "What’s something you do in the morning that slows you down?" },
  { "normal": "How many apps are currently running in the background?", "imposter": "How many of them do you *actually* use every day?" },
  { "normal": "How often do you wash your bedsheets?", "imposter": "How many days in a row have you slept without changing them?" },
  { "normal": "What’s your go-to way to celebrate small wins?", "imposter": "What’s something you do even when there’s nothing to celebrate?" },
  { "normal": "How many times a day do you use search engines?", "imposter": "How many times a day do you Google stuff you already know?" },
  { "normal": "What’s your favorite spot to hang out on weekends?", "imposter": "What’s a place you avoid unless you’re forced to go?" },
  { "normal": "How many items are in your online shopping cart?", "imposter": "How many items are in your saved-for-later list?" },
  { "normal": "What’s your favorite thing to binge on weekends?", "imposter": "What’s something you binge but feel bad about later?" },
  { "normal": "How many people do you follow on social media?", "imposter": "How many of them would you unfollow if no one noticed?" },
  { "normal": "How long do you take to get out of bed after waking up?", "imposter": "How many minutes do you lie there doomscrolling first?" },
  { "normal": "What’s your favorite way to recharge socially?", "imposter": "What’s a social thing you often cancel last-minute?" },
  { "normal": "How many browser windows do you have open right now?", "imposter": "How many open windows do you not even remember opening?" },
  { "normal": "What’s a song you could play on repeat for hours?", "imposter": "What’s a song that always gets stuck in your head, even if you hate it?" },
  { "normal": "How many people do you message every day?", "imposter": "How many people do you leave on read daily?" },
  { "normal": "What’s your favorite holiday tradition?", "imposter": "What’s a tradition you fake excitement for?" },
  { "normal": "How many hours do you spend online on weekends?", "imposter": "How many hours do you spend *pretending* to be productive online?" },
  { "normal": "What’s your favorite thing to do with your phone when you’re bored?", "imposter": "What’s something you do on your phone that feels like a waste of time?" },
  { "normal": "How many people have you texted this week?", "imposter": "How many conversations are left hanging in your inbox right now?" },
  { "normal": "What’s your favorite delivery app?", "imposter": "What’s an app you’ve kept installed even though you don’t use it anymore?" },
  { "normal": "How many messages do you get on a busy day?", "imposter": "How many group chats do you mute during a busy day?" },
  { "normal": "How many unread emails do you currently have?", "imposter": "How many newsletters did you sign up for but never read?" },
  { "normal": "What’s your ideal sleep schedule?", "imposter": "What’s the weirdest time you’ve gone to sleep lately?" },
  { "normal": "How many steps do you walk in your house daily?", "imposter": "How many steps do you avoid by doing everything from bed?" },
  { "normal": "What’s your favorite way to waste time on your computer?", "imposter": "What’s something you spend hours on without realizing?" },
  { "normal": "How many different apps do you use just for chatting?", "imposter": "How many chats do you open and then close without replying?" },
  { "normal": "What’s your favorite app to check during short breaks?", "imposter": "What’s an app you check out of habit but don’t enjoy?" },
  { "normal": "How many alarms are currently set on your phone?", "imposter": "How many alarms have weird or funny names?" },
  { "normal": "How many browser bookmarks do you have?", "imposter": "How many of those bookmarks have you never actually opened?" },
  { "normal": "What’s your favorite food to eat when no one’s watching?", "imposter": "What’s a food combo you like but would never admit to in public?" },
  { "normal": "How many songs are in your 'Liked' playlist?", "imposter": "How many songs do you like but skip every time they come on?" },
  { "normal": "What’s the weirdest thing on your phone right now?", "imposter": "What’s a screenshot you've saved but can’t explain?" },
  { "normal": "How many items are in your trash or recycle bin right now?", "imposter": "How many files do you keep 'just in case' but never open?" },
  { "normal": "What’s your go-to drink order at a café?", "imposter": "What’s a drink you only order because someone else likes it?" },
  { "normal": "How many different rooms have you worked from at home?", "imposter": "How many times have you worked from bed this week?" },
  { "normal": "What’s your favorite guilty pleasure movie?", "imposter": "What’s a movie you rewatch even though you know it’s bad?" },
  { "normal": "How many open apps are on your phone right now?", "imposter": "How many of them are just running because you forgot to close them?" },
  { "normal": "How many screens do you use while relaxing?", "imposter": "How many screens do you use at once without even thinking about it?" },
  { "normal": "What’s your favorite type of ice cream?", "imposter": "What’s an ice cream flavor you pretend to like around others?" },
  { "normal": "How often do you update your apps?", "imposter": "How many apps are pending updates right now?" },
  { "normal": "How many hours do you spend lying down in a day?", "imposter": "How many of those hours are spent doing absolutely nothing?" },
  { "normal": "What’s your favorite public place to hang out?", "imposter": "What’s a place you go just to kill time, not because you enjoy it?" },
  { "normal": "How many things are on your desk right now?", "imposter": "How many of those things haven’t moved in weeks?" },
  { "normal": "How many active browser tabs is too many?", "imposter": "How many tabs do you keep open purely for emotional support?" },
  { "normal": "What’s your favorite way to kill time while waiting?", "imposter": "What’s something you do in public just to look busy?" },
  { "normal": "How many people in your contact list do you actually talk to?", "imposter": "How many contacts have names you don’t even recognize?" },
  { "normal": "How many times do you order food in a typical week?", "imposter": "How many times have you ordered food just because you were bored?" },
  { "normal": "What’s your favorite genre of movie?", "imposter": "What’s a movie genre you always avoid even if friends suggest it?" },
  { "normal": "How many phone chargers do you own?", "imposter": "How many chargers have you borrowed and never returned?" },
  { "normal": "What’s your go-to way to spend a quiet evening?", "imposter": "What’s something you only do when you’re completely home alone?" },
  { "normal": "How many photos are on your lock screen rotation?", "imposter": "How many times have you kept a weird or meme image as your wallpaper?" },
  { "normal": "What’s your favorite online distraction?", "imposter": "What’s something online that always sucks you in unintentionally?" },
  { "normal": "How many unread notifications bother you enough to clear?", "imposter": "How many red dots or badges are on your phone right now?" },
  { "normal": "What’s your favorite fast food place?", "imposter": "What’s a fast food chain you eat at but don’t really enjoy?" },
  { "normal": "How many tabs do you keep open as a reminder?", "imposter": "How many of those tabs are things you’ll realistically never return to?" },
  { "normal": "What’s your favorite way to spend a weekend morning?", "imposter": "What’s something you only do on weekend mornings because you feel guilty otherwise?" },
  { "normal": "How many passwords do you have saved in your browser?", "imposter": "How many accounts do you share with someone else?" },
  { "normal": "What’s your favorite time of day to be outside?", "imposter": "What time of day do you stay indoors no matter what?" },
  { "normal": "How many social accounts do you post on regularly?", "imposter": "How many burner or second accounts have you created over time?" },
  { "normal": "What’s your favorite type of mobile game?", "imposter": "What’s a game you’re lowkey addicted to but don’t talk about?" },
  { "normal": "How many pairs of socks do you own?", "imposter": "How many unmatched socks are hiding in your laundry pile?" },
  { "normal": "What’s your favorite way to spend a lazy Sunday?", "imposter": "What’s something you do on Sundays that feels like a waste but you still do it?" },
  { "normal": "How many tabs do you reopen every time you start your computer?", "imposter": "How many times do you just hit 'restore all' without even checking?" },
  { "normal": "What’s your favorite thing to binge-watch alone?", "imposter": "What’s something you only watch when no one else is around?" },
  { "normal": "How many unread WhatsApp or Messenger messages do you have?", "imposter": "How many times have you read a message and never replied?" },
  { "normal": "How many apps are on your home screen?", "imposter": "How many of them are there just because you forgot to remove them?" },
  { "normal": "What’s your favorite spot in your house?", "imposter": "What’s a part of your home that’s basically storage now?" },
  { "normal": "How many times do you hit 'remind me later' for updates?", "imposter": "How many updates are currently pending on your device?" },
  { "normal": "What’s your most-used emoji?", "imposter": "What’s an emoji you overuse even though it doesn't really fit?" },
  { "normal": "How many devices are logged into your streaming account?", "imposter": "How many of those devices aren’t actually yours?" },
  { "normal": "What’s your favorite time to clean your room?", "imposter": "What’s the messiest time of day in your space?" },
  { "normal": "How many people have your Wi-Fi password?", "imposter": "How many people are probably still using your Wi-Fi?" },
  { "normal": "What’s your favorite flavor of chips?", "imposter": "What’s a snack you buy even though you never finish it?" },
  { "normal": "How many apps have you downloaded this month?", "imposter": "How many apps did you try once and never open again?" },
  { "normal": "What’s your favorite part of your daily routine?", "imposter": "What’s a part of your routine you always rush through?" },
  { "normal": "How many windows do you keep open during a work session?", "imposter": "How many of them are actually work-related?" },
  { "normal": "How many things do you usually carry when leaving the house?", "imposter": "How many times do you check your pockets or bag before leaving?" },
  { "normal": "What’s your favorite thing to do when stuck in traffic?", "imposter": "What’s something you’ve done in traffic that you'd never admit?" },
  { "normal": "How many different passwords do you use regularly?", "imposter": "How many passwords do you know by heart?" },
  { "normal": "What’s your favorite midnight activity?", "imposter": "What’s something you start doing late at night that you instantly regret?" },
  { "normal": "How many tabs do you open when doing research?", "imposter": "How many of those tabs are totally unrelated to your task?" },
  { "normal": "How many hours a week do you spend watching short videos?", "imposter": "How many hours do you spend *trying* not to watch short videos?" },
  { "normal": "What’s your favorite guilty pleasure app?", "imposter": "What’s an app you’d uninstall if someone else looked at your phone?" },
  { "normal": "How many times do you hit snooze in the morning?", "imposter": "How many alarms do you *pretend* to set but never wake up to?" },
  { "normal": "What’s your favorite comfort TV show?", "imposter": "What’s a show you’ve rewatched way too many times?" },
  { "normal": "How many emails do you delete without reading?", "imposter": "How many emails do you keep just so your inbox looks busy?" },
  { "normal": "What’s your favorite type of clothing to wear at home?", "imposter": "What’s a piece of clothing you own that you'd never wear outside?" },
  { "normal": "How many playlists do you listen to regularly?", "imposter": "How many playlists do you skip through without playing anything?" },
  { "normal": "What’s your favorite way to spend time while commuting?", "imposter": "What’s something weird you’ve seen or done during a commute?" },
  { "normal": "How many steps are in your evening routine?", "imposter": "How many of those steps do you skip when you’re too tired?" },
  { "normal": "What’s your favorite music streaming platform?", "imposter": "What’s a platform you use just because you’re too lazy to switch?" },
  { "normal": "How many devices do you own personally?", "imposter": "How many of them are slightly broken but you still use them?" },
  { "normal": "What’s your favorite part of your morning routine?", "imposter": "What’s the part of your morning you always rush or skip?" },
  { "normal": "How many tabs do you keep open while shopping online?", "imposter": "How many times do you add something to cart and never buy it?" },
  { "normal": "How many notifications do you check first after waking up?", "imposter": "How many apps do you check before even brushing your teeth?" },
  { "normal": "What’s your favorite online activity when procrastinating?", "imposter": "What’s something you do to avoid starting a task but pretend it’s productive?" },
  { "normal": "How many people have access to your streaming accounts?", "imposter": "How many times have you used someone else’s account without asking?" },
  { "normal": "What’s your favorite spot to sit in a movie theater?", "imposter": "What’s something you do during movies that might annoy other people?" },
  { "normal": "How many people do you talk to every day?", "imposter": "How many people do you *wish* you didn’t have to talk to daily?" },
  { "normal": "How often do you update your profile pictures?", "imposter": "How many photos have you taken just for a new profile picture but never used?" },
  { "normal": "How many times do you check the weather app in a day?", "imposter": "How many times do you check it and still forget to bring an umbrella?" },
  { "normal": "How many browser tabs are you emotionally attached to?", "imposter": "How many tabs are open *just* because you forgot to close them?" },
  { "normal": "What’s your favorite spot to relax outdoors?", "imposter": "What’s a public place you go to just to be alone?" },
  { "normal": "How many old apps are still on your phone?", "imposter": "How many apps do you keep even though they don’t work anymore?" },
  { "normal": "What’s your go-to background noise when working?", "imposter": "What’s something you put on as background but secretly end up watching?" },
  { "normal": "How many drafts do you have saved on social media?", "imposter": "How many times have you written a post and deleted it before sharing?" },
  { "normal": "How many different mugs or cups do you use regularly?", "imposter": "How many cups have you left unwashed for more than a day?" },
  { "normal": "What’s your favorite way to waste time online?", "imposter": "What’s something online you *pretend* is educational?" },
  { "normal": "How many people have you video called this month?", "imposter": "How many video calls have you dodged recently?" },
  { "normal": "What’s your favorite rainy day activity?", "imposter": "What’s something you avoid completely when it rains?" },
  { "normal": "How many pairs of shoes do you own?", "imposter": "How many shoes do you own but don’t wear anymore?" },
  { "normal": "What’s your favorite type of food to order when you're tired?", "imposter": "What’s a food you order just because it’s fast, not because you like it?" },
  { "normal": "How many times a day do you open your phone without thinking?", "imposter": "How many times have you unlocked your phone and forgotten why?" },
  { "normal": "What’s your favorite online purchase this year?", "imposter": "What’s something you bought online and instantly regretted?" },
  { "normal": "How many tabs or documents do you usually have open while working?", "imposter": "How many of them are just there to *look* like you’re busy?" },
  { "normal": "What’s your favorite way to procrastinate before a deadline?", "imposter": "What’s the most elaborate thing you've done to avoid one small task?" },
  { "normal": "How many unread notifications do you tolerate before clearing them?", "imposter": "How many notifications are you currently ignoring on purpose?" },
  { "normal": "What’s your favorite thing to do when the Wi-Fi is down?", "imposter": "What’s the first app you try, even when you know there’s no internet?" },
  { "normal": "How many group chats are you active in?", "imposter": "How many groups are muted and completely ignored?" },
  { "normal": "What’s your favorite way to spend a lunch break?", "imposter": "What’s something you do during lunch that makes the day feel longer?" },
  { "normal": "How many notifications do you get per hour on average?", "imposter": "How many of those do you actually care about?" },
  { "normal": "What’s your go-to outfit when you don’t want to think?", "imposter": "What’s a piece of clothing you wear just because it's always clean?" },
  { "normal": "How many times a day do you double-check if you locked the door?", "imposter": "How many times have you *not* checked and worried later anyway?" },
  { "normal": "What’s your favorite fast food order?", "imposter": "What’s a food you eat even when you know it’s going to mess you up later?" },
  { "normal": "How many playlists have you made?", "imposter": "How many playlists are just slight variations of each other?" },
  { "normal": "How many items are on your desktop or home screen?", "imposter": "How many of them do you pretend you'll sort 'later'?" },
  { "normal": "What’s your favorite low-effort meal?", "imposter": "What’s a food you pretend takes effort but really doesn’t?" },
  { "normal": "How many tabs do you open when planning a trip?", "imposter": "How many of those tabs stay open long after the trip is over?" },
  { "normal": "What’s your favorite part of staying in?", "imposter": "What’s a reason you use to cancel going out that isn’t always true?" },
  { "normal": "How many alarms do you have saved on your phone?", "imposter": "How many of those alarms are set at weirdly specific times?" },
  { "normal": "What’s your favorite way to relax without a screen?", "imposter": "What’s the last thing you did off-screen that actually felt boring?" },
  { "normal": "How many cloud storage accounts do you use?", "imposter": "How many of those are totally full or disorganized?" },
  { "normal": "How many things do you have pinned to your browser or taskbar?", "imposter": "How many of them do you *never* actually click on?" },
  { "normal": "What’s your favorite online video genre?", "imposter": "What’s a type of video you watch but would never recommend?" },
  { "normal": "How many hours a week do you spend doing something creative?", "imposter": "How many of those hours are just *thinking* about being creative?" },
  { "normal": "What’s your go-to way to avoid being bored in public?", "imposter": "What’s something fake you’ve done to look busy in public?" }
]
